Add PUT endpoint for submitting DOI information.
CSCfi/metadata-submitter pull request #423
Opened 2022-05-12 10:55 UTC by csc-felipe

### Description

Add PUT endpoint for submitting DOI information.
Previously, DOI could be added to a folder only with a patch request.
The new endpoint makes it easier to format requests that add or update DOI information.

### Related issues

Closes #384
### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Added a new endpoint for submitting DOI information

### Testing

- [x] Unit Tests

### Mentions

2022-05-12 13:09 UTC, genie9 requested changes
The new endpoint is simple and clear, good job! This change though needs to be addressed in integration tests. I do not think new tests are needed if old ones would be adjusted to use a new endpoint.

2022-05-12 13:20 UTC, genie9 commented
A new endpoint needs to be added to swagger doc https://github.com/CSCfi/metadata-submitter/blob/497bf5982e527fe4ea5ad584fce593c293424bfb/docs/specification.yml#L935

2022-05-13 06:14 UTC, teemukataja approved these changes
Could we add a new case also to the python integration tests https://github.com/CSCfi/metadata-submitter/blob/feature/publish_doi_metax_folder/tests/integration/run_tests.py

2022-05-13 06:14 UTC, teemukataja commented on metadata_backend/api/handlers/folder.py
> +        LOG.info(doi_info)
```suggestion
```
This was probably left here from testing? Can be removed

2022-05-17 07:25 UTC, csc-felipe commented
Rebased, and removed `dataset` from minimal publication, as it's not required.

2022-05-17 16:25 UTC, genie9 approved these changes

2022-05-18 06:51 UTC, csc-felipe commented on tests/integration/run_tests.py
> +
Let's update it when we deprecate the `patch` endpoint.

I removed the `dataset` in the previous push, as it apparently is not currently required.

2022-05-18 08:20 UTC, teemukataja approved these changes

2022-05-18 08:48 UTC, merged