Make metax errors visible
CSCfi/metadata-submitter pull request #453
Opened 2022-05-27 15:20 UTC by csc-felipe

### Description

Refactored Metax error handling, so error becomes visible to end user, only in publication endpoint.

### Related issues

- Fixes #382

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Changes Made

- Remove lingering error page references
- Remove broken HEAD request to check for connection - Metax doesn't support HEAD requests
- Remove duplicate code
- Let Metax errors surface
- Catches unexpected errors and return JSON Problem detail
- Update Docker compose version to 3.4 as the `build target` parameter was introduced in that version
- Add Metax connection check to more endpoints.
- Ignore and log metax errors in Object API endpoints

### Testing

Existing tests should continue to work.

- [x] Tests do not apply

### Mentions

2022-05-30 08:51 UTC, csc-felipe commented
I wonder why integration tests fail. They all pass in dev env.

2022-05-31 14:23 UTC, genie9 commented
could you please change the base to branch `refactor/json-error-handling` for now until we sort out what to do with braking changes caused to frontend

2022-05-31 15:48 UTC, csc-felipe commented
> could you please change the base to branch `refactor/json-error-handling` for now until we sort out what to do with braking changes caused to frontend

Done

2022-06-03 09:33 UTC, genie9 requested changes

2022-06-03 13:03 UTC, csc-felipe commented on metadata_backend/api/handlers/submission.py
> -        await metax_handler.check_connection()
This doesn't guarantee that the next request will succeed. But sure, we can leave it there, and make a better solution in another change.

2022-06-07 06:59 UTC, genie9 requested changes

2022-06-08 12:59 UTC, genie9 approved these changes

2022-06-08 16:48 UTC, merged