Feature/token auth
CSCfi/metadata-submitter pull request #583
Opened 2022-09-21 11:53 UTC by teemukataja

### Description
Adds support for using the REST API with `Bearer` tokens issued by the configured `OIDC_URL`.

### Related issues
Closes #468 

### Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update (this needs a follow up PR)

### Changes Made

- refactored some `callback()` code in `auth.py` into functions, so that they can be re-used in the middleware
- added new case to middleware which checks for the existence of a `Bearer` token, and if one exists, it validates it at the configured `OIDC_URL` and gets back the user profile, which is used to create the user context for the duration of the request

### Testing

- [x] Unit Tests
- [x] Integration Tests
- [x] Manual Testing

### Mentions

2022-09-21 11:58 UTC, teemukataja commented on metadata_backend/api/auth.py
> +from typing import Any, Dict, List, Union
I know we don't like `Any`, but it comes from `oidcrp` which is oblivious to the userinfo response type `userinfo: Dict[str, Any]`, so I put this in there :smile:

2022-09-21 12:18 UTC, csc-felipe commented
There was a comment on the issue #468:

> We would need to restrict access so that users cannot create new users, or have permissions we were not expecting them to.

@teemukataja, did you have any thoughts about this?

2022-09-21 12:23 UTC, csc-felipe commented on metadata_backend/api/middlewares.py
> +    user_data: Dict[str, Union[List[Dict[str, str]], str]] = await single_session._create_user_data(userinfo)
Should we have a type alias for this, as it seems to repeat? 
e.g. `UserData = Dict[str, Union[List[Dict[str, str]], str]]`

2022-09-21 13:02 UTC, teemukataja commented
> There was a comment on the issue #468:
> 
> > We would need to restrict access so that users cannot create new users, or have permissions we were not expecting them to.
> 
> @teemukataja, did you have any thoughts about this?

Bearer tokens provide the same permissions as frontend login

2022-09-22 06:55 UTC, blankdots commented
> Bearer tokens provide the same permissions as frontend login

I would prefer if we would think of a way to restrict them, only to known users that either exist in the db or are added (e.g. by an admin in the db)

2022-09-22 10:24 UTC, teemukataja commented
> > Bearer tokens provide the same permissions as frontend login
> 
> I would prefer if we would think of a way to restrict them, only to known users that either exist in the db or are added (e.g. by an admin in the db)

So a user can use the API if they have either first logged in via frontend, or had an admin manually add their username to the db?

2022-09-22 10:35 UTC, blankdots commented
> So I'm thinking why does the API need to be more restricted than the frontend?

at the moment it does not.

The only scenarios i could think of is to prevent abuse, e.g. automatic deletion and submission, but that can be done in front-end as well.
We can leave it like this, and we can figure out particular use cases on top of it, if it needs restricting.

2022-09-22 11:45 UTC, csc-felipe approved these changes

2022-09-23 06:48 UTC, blankdots requested changes

2022-09-23 06:48 UTC, blankdots commented on CHANGELOG.md
> +- Removed `OIDC_ENABLED` testing variable which can cause misconfiguration incidents
this should go under removed section

2022-09-23 06:48 UTC, blankdots commented on metadata_backend/api/auth.py
> +            "projects": [],
should this be a `ProjectList` type as used in other places as well ?

2022-09-23 06:55 UTC, blankdots commented on metadata_backend/api/auth.py
> +            "projects": [],
my bad this was defined already and did not see it.

2022-09-23 07:02 UTC, blankdots approved these changes

2022-09-23 08:13 UTC, merged