Feature/update typing
CSCfi/metadata-submitter pull request #790
Opened 2023-08-29 06:44 UTC by gimppa

### Description
Updated type annotations all around. Mostly changed dict and list type annotations to be Dict[something] and List[something].

### Related issues

Fixes #789 github workflows

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Testing

- [x] Tests do not apply

2023-08-29 07:23 UTC, csc-felipe commented
Why should we use `Dict` and `List` instead of `dict` and `list` in Python 3.11? Which makes me think that perhaps we [should set `python-version` for `mypy`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-python_version).

2023-08-31 16:33 UTC, csc-jm requested changes
I think what @csc-felipe commented is a good point. If we're updating the typing, we might as well do it with the current best practice while we're at it (as long as it's not an unnecessarily long task). So while the built-in `typing` class still exists, it's been deprecated by now as proposed in PEP 585. So you would have `list`, `dict` etc. or then `collections.abc.Callable` and `collections.abc.Iterator`. 

However, it seems the types `Any`, `Optional`, `TypedDict` and `TypeVar` which we still have in our code (at least I found in this PR) are still to be imported from `typing` 🤔

2023-08-31 16:33 UTC, csc-jm commented on metadata_backend/api/handlers/rems_proxy.py
> +# : Dict[str, Dict[str, Dict[str, Any] | Any] | Any]
Not quite sure what this is

2023-08-31 16:33 UTC, csc-jm commented on metadata_backend/api/handlers/restapi.py
> +from typing import Any, AsyncIterator, Dict, Iterator, List, Optional, Tuple
So according to PEP 585, these would instead be
- dict
- list
- tuple
- collections.abc.AsyncIterator
- collections.abc.Iterator

However, `Any` and `Optional` would still be imported from `typing`

2023-09-05 14:09 UTC, gimppa commented on metadata_backend/api/handlers/rems_proxy.py
> +# : Dict[str, Dict[str, Dict[str, Any] | Any] | Any]
This is a mistake :laughing:

2023-09-05 19:20 UTC, csc-felipe approved these changes
Looks good :)

2023-09-05 19:22 UTC, csc-felipe commented
Approved, but you still have to click on the **three dots > dismiss review** from Joonatan's requested changes.

2023-09-06 15:07 UTC, csc-jm approved these changes
Now everything looks good to me as well :P

2023-09-06 15:08 UTC, merged